// GET ALL ACTUALITÉS
export const GET_ALL_ACTUALITÉS_SUCCEED ="GET_ALL_ACTUALITÉS_SUCCED"
export const GET_ALL_ACTUALITÉS_FAILED ="GET_ALL_ACTUALITÉS_FAILED"

// GET  ACTUALITÉ
export const GET_ACTUALITÉ_SUCCEED ="GET_ACTUALITÉ_SUCCED"
export const GET_ACTUALITÉ_FAILED ="GET_ACTUALITÉ_FAILED"